from core.serializers.post_like import PostLikeSerializer
from core.serializers.post_comment import PostCommentSerializer
from core.serializers.post_tag import PostTagSerializer
from core.serializers.user import UserSerializer
from core.serializers.post import PostSerializer
from core.serializers.author import AuthorSerializer
from core.serializers.publisher import PublisherSerializer
from core.serializers.book_tag import BookTagSerializer
from core.serializers.book import BookSerializer
from core.serializers.read_book import ReadBookSerializer
from core.serializers.favorite_phrase import FavoritePhrase
from core.serializers.favorite_phrase_like import FavoritePhraseLikeSerializer